// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZg95WciVuvUtB9OEoIuLTn8SvD9Bhog',
    appId: '1:537850001579:web:f65b4f17cd54677a3b5fee',
    messagingSenderId: '537850001579',
    projectId: 'firease-web',
    authDomain: 'firease-web.firebaseapp.com',
    storageBucket: 'firease-web.appspot.com',
    measurementId: 'G-X7XXHYCEZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTMw12SdNXxtE9yeuQFkLdhskUDori0j0',
    appId: '1:537850001579:android:a3eed489e32aa0bf3b5fee',
    messagingSenderId: '537850001579',
    projectId: 'firease-web',
    storageBucket: 'firease-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTg-KgEHovu8AnDMJcHSNmxKgebikft00',
    appId: '1:537850001579:ios:119a0f9682e4d78c3b5fee',
    messagingSenderId: '537850001579',
    projectId: 'firease-web',
    storageBucket: 'firease-web.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTg-KgEHovu8AnDMJcHSNmxKgebikft00',
    appId: '1:537850001579:ios:18d6ec5ffbc8499e3b5fee',
    messagingSenderId: '537850001579',
    projectId: 'firease-web',
    storageBucket: 'firease-web.appspot.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
